Add option to the mod menu for compatibillity
JonathanTroyer/Progress-Renderer pull request #29
Opened 2024-03-29 00:40 UTC by XenoTheStrange

Users might want to render maps which aren't technically player homes. I know I do!

I've been using DeepRim for awhile and couldn't get it to work and render images for underground maps, so I looked in the source to find out why. Turns out to be a single if-statement which returns -_-.
Now it'll check for a mod config option which allows it to capture images of other maps.

2024-03-29 03:29 UTC, XenoTheStrange commented
I'm thinking of adding an option that will also sort screenshots based on the name (ToString) of the map they're on so things are easier to navigate. Rn it mixes up different maps, giving them the same name but adding "alt-1" as a suffix.

2024-04-02 19:16 UTC, XenoTheStrange commented
Hmmmmmm I might just exclude the .csproj file for sake of conflicts. This is the versoin of progress renderer that's on steam rn, right?

2024-04-02 19:31 UTC, XenoTheStrange commented
Removed .csproj files from the commit

2024-04-02 19:37 UTC, XenoTheStrange commented
I smushed the edits into one little non-conflicting commit.
I am not very good at the github.

2024-04-02 19:49 UTC, XenoTheStrange commented
After rendering the mod yanks you to another map sometimes which is super annoying. Might look into that.

2024-04-02 19:53 UTC, XenoTheStrange commented
![image](https://github.com/JonathanTroyer/Progress-Renderer/assets/48196283/57c45fa7-0d7b-441c-954d-78fb002bc0dc)

2024-04-02 20:09 UTC, XenoTheStrange commented
Working on fixing race condition that causes the map to switch to a random rendered one after rendering....

2024-04-02 20:54 UTC, XenoTheStrange commented
![image](https://github.com/JonathanTroyer/Progress-Renderer/assets/48196283/1e45e768-78fb-431a-96c0-30b8ce1791b0)

After the first couple of renders it just _doesn't_ change the current map back to the remembered map, despite running the code which would do so: `Current.Game.CurrentMap = rememberedMap;`

2024-04-02 21:40 UTC, XenoTheStrange commented
The problem of it switching to a random map is due to several instances of the DoRender function running at the same time, so while one changes the map to render it the other is saving _that_ map as the one to return to instead of the proper one:
![image](https://github.com/JonathanTroyer/Progress-Renderer/assets/48196283/c4a247fc-244a-4e6e-a464-f97243829d44)

2024-04-02 22:04 UTC, XenoTheStrange commented
This error actually causes problems: It will make duplicate captures of some maps while ignoring others.
Pretty sure this problem applies whenever there are more than 2 maps being captured.

2024-04-02 22:15 UTC, XenoTheStrange commented
I submitted an issue with the error I encountered, but beyond that this pull is ready.

2024-04-02 22:24 UTC, XenoTheStrange commented
.... Merged your bump to 1.5 that happened to occur recently. All done.

2024-04-04 20:40 UTC, JonathanTroyer requested changes
Looks great besides that one label. Very good first PR, thank you!

2024-04-04 20:40 UTC, JonathanTroyer commented on Common/Languages/English/Keyed/All.xml
> +	<LPR_SettingsRenderNonPlayerHomes>Non-PlayerHome Maps</LPR_SettingsRenderNonPlayerHomes>
Change to "Non-colony maps"

2024-04-04 20:46 UTC, XenoTheStrange commented on Common/Languages/English/Keyed/All.xml
> +	<LPR_SettingsRenderNonPlayerHomes>Non-PlayerHome Maps</LPR_SettingsRenderNonPlayerHomes>
Done

2024-04-04 20:47 UTC, JonathanTroyer approved these changes

2024-04-04 20:51 UTC, merged